url: https://lumbersaur.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Benjamin Jablonowski Portfolio
email: bjablonowski@hotmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Benjamin Jablonowski
  pic: Benjamin
  position: Bloc Web Development Bootcamp Student
  social:
    - title: github
      url: https://github.com/Lumbersaur
    - title: linkedin
      url: https://www.linkedin.com/in/benjamin-jablonowski/

- name: Myself
  pic: Lumberjack
  position: Retired Lumberjack
  social:
    - title: github
      url: https://github.com/Lumbersaur
    - title: linkedin
      url: https://www.linkedin.com/in/benjamin-jablonowski/

- name: And I
  pic: myCooking
  position: Nutrition Nut
  social:
    - title: github
      url: https://github.com/Lumbersaur
    - title: linkedin
      url: https://www.linkedin.com/in/benjamin-jablonowski/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/jekyll
  - title: linkedin
    url: https://www.linkedin.com/in/benjamin-jablonowski/

# Postal address (add as many lines as necessary)
address:
  - line: 225 Central Ave SW Apt. 1407
  - line: Atlanta, GA 30303

# Build settings
markdown: kramdown
permalink: pretty